apiVersion: apps/v1
kind: Deployment
metadata:
  name: swin-reid-embedding-service
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      application: swin-reid-embedding-service
  template:
    metadata:
      labels:
        application: swin-reid-embedding-service
    spec:
      serviceAccountName: default-editor
{{- if .Values.gpu.enabled  }}
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-tesla-t4
{{- end }}
      containers:
        - name: swin-reid-embedding-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: GPU
              value: {{ if .Values.gpu.enabled }}"true"{{ else }}"false"{{ end }}
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 4Gi
{{- if .Values.gpu.enabled  }}
              nvidia.com/gpu: 1
{{- end }}