apiVersion: v1
kind: Service
metadata:
  name: swin-reid-embedding-service
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    application: swin-reid-embedding-service
  ports:
    - name: http
      port: 80
      targetPort: 8000
