apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: swin-reid-embedding-service
  namespace: {{ .Release.Namespace }}
spec:
  gateways:
    - teknoir/teknoir-gateway
  hosts:
    - '*'
  http:
    - match:
        - uri:
            prefix: {{ .Values.basePath | quote }}
      route:
        - destination:
            host: swin-reid-embedding-service.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 80
